### ISSUE TITLE
关于自蒸馏与EMA的问题

### ISSUE THREAD

**Issue by XuanjiaZ** [NJU-LHRS/official-CMID#15]
你好
请问结构中的自蒸馏是只使用了EMA实现的吗
EMA实现的代码在哪里呢

**Comment by XuanjiaZ** [comment]
我好像已经找到了

**Comment by XuanjiaZ** [comment]
> Hi~您好. EMA相关代码是由`/Pretrain/models/pretrain_model.py`下`line 76 MomentumUpdater`以及hook(`Pretrain\Exploring\hook\EMA_hook.py`)一同完成的. 自蒸馏思想体现在EMA以及Loss的设计上.Loss可以参考`/Pretrain/models/loss_utils.py`下的`LocalLoss`.


感谢!,已经找到了

**Comment by pUmpKin-Co** [comment]
Closed as long periods of inactivity, feel free to reopen if there is any problem.
