### ISSUE TITLE
Code Question: When masking an image

### ISSUE THREAD

**Issue by lhj-3** [NJU-LHRS/official-CMID#18]
I'm looking at your research. Thank you for your wonderful work.

However, a question arises while looking at the code, leaving an issue.
During masking processing, "Blockwise Mask Generator" confirmed that changing to mean value instead of zero resulted in discrepancy between image and mask.

Is there a process to deal with afterwards because there is something I didn't find??
Or is this error updated??

Thank you.

**Comment by ayh456** [comment]
Hello, I would like to ask how the T-sne visualization mentioned in your paper is implemented, is there any code? Thank you

**Comment by pUmpKin-Co** [comment]
Hi~ @lhj-3 Thanks for your interest.
I don't actually understand your questions. We utilize the average mean to fill the masked patches and after patch embedding we add mask token to the masked patches and regress them as training target.
The mask is just used for collect the correct masked patches for loss computation.
I hope my answer can help you.

**Comment by pUmpKin-Co** [comment]
Hi~ @ayh456. I'm sorry I don't have access to the original project environment at this moment.
You can refer this [implementations](https://github.com/open-mmlab/mmpretrain/blob/main/tools/visualization/vis_tsne.py) for t-sne visualization. I mostly borrow the code from this implementation.

**Comment by pUmpKin-Co** [comment]
Closed as long periods of inactivity, feel free to reopen if there is any problem.
