### ISSUE TITLE
Acknowledge Using A2MIM (or OpenMixup Implementations) in CMID

### ISSUE THREAD

**Issue by Lupin1998** [NJU-LHRS/official-CMID#2]
Dear authors,

Thanks for the great work of the self-supervised framework [CMID](https://arxiv.org/abs/2304.09670) for remoting sensing representation learning, and congratulations 👍 on being accepted to [IEEE TGRS](https://ieeexplore.ieee.org/document/10105625). I have added CMID to our [Awesome-MIM](https://github.com/Lupin1998/Awesome-MIM). However, I would like to ask you to add acknowledgment of using [A2MIM](https://github.com/Westlake-AI/A2MIM) or [OpenMixup](https://github.com/Westlake-AI/openmixup) implementation (e.g., [loss_utils.py](https://github.com/NJU-LHRS/official-CMID/blob/main/Pretrain/models/loss_utils.py) and [mim_utils.py](https://github.com/NJU-LHRS/official-CMID/blob/main/Pretrain/models/mim_utils.py)) in [Acknowledgement](https://github.com/NJU-LHRS/official-CMID/tree/main#acknowledgement) of CMID repository. I am glad to find that CMID adopted the proposed RGB mean input and the Focal Frequency loss for MIM in [A2MIM](https://arxiv.org/abs/2205.13943) (as described in Sec. III-B of CMID). Recently, A2MIM has been accepted to ICML'2023. I really appreciate your using and acknowledging A2MIM (as follows).

Thanks
Siyuan Li

```markdown
## Acknowledgement

+ Many thanks to the following repos: [Remote-Sensing-RVSA](https://github.com/ViTAE-Transformer/Remote-Sensing-RVSA)、[iBOT](https://github.com/bytedance/ibot)、[A2MIM](https://github.com/Westlake-AI/A2MIM)、[core-pytorch-utils](https://github.com/serend1p1ty/core-pytorch-utils)、[solo-learn](https://github.com/vturrisi/solo-learn)、[OpenMixup](https://github.com/Westlake-AI/openmixup)、[timm](https://github.com/huggingface/pytorch-image-models)、[Adan](https://github.com/sail-sg/Adan).
```

**Comment by pUmpKin-Co** [comment]
Hi～Thanks for your reminder. I’m feel so sorry for my mistake. I will update the acknowledgement as soon as I finish my Labor Day Holiday. I will let you know as soon as the update is available! Once again, I apologize for my carelessness.

**Comment by Lupin1998** [comment]
Hello, @pUmpKin-Co. Thanks for your reply and adding acknowledgement 😄. I am on Labor Day Holiday, too. I wish you have a good holiday~

**Comment by pUmpKin-Co** [comment]
Hi~We have updated the acknowledgement. Thans for your reminder and awesome implementations!

**Comment by Lupin1998** [comment]
Thanks very much for updating the acknowledgement! I have no more questions and will close this issue.
