### ISSUE TITLE
想问一下具体的环境配置，能否提供一些有用的具体的库和python版本？

### ISSUE THREAD

**Issue by ttaohe** [NJU-LHRS/official-CMID#3]

**Comment by pUmpKin-Co** [comment]
Hi~你好，我们环境配置python版本是3.9.12，pytorch版本是1.12.0.
其他具体的环境配置请参考[environment.yml](https://github.com/NJU-LHRS/official-CMID/blob/main/Pretrain/environment.yml). conda支持通过`.yml`文件直接创建环境，请参考[conda文档](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#:~:text=%2D%2Dhelp.-,Creating%20an%20environment%20from%20an%20environment.yml%20file,-%EF%83%81).

**Comment by pUmpKin-Co** [comment]
Closed due to long periods of inactivity, can be reopened at any time if there is any problem.
