### ISSUE TITLE
关于下游任务微调的问题

### ISSUE THREAD

**Issue by busbyjrj** [NJU-LHRS/official-CMID#31]
作者您好，感谢团队的开源贡献。想请教下预训练完成后，向下游任务的微调，代码中注释掉了一部分冻结参数的代码，想确定下是否在下游任务微调的过程中使用到了这部分，谢谢。

祝好！

**Comment by pUmpKin-Co** [comment]
您好。

请问具体是哪里呀。

**Comment by busbyjrj** [comment]
https://github.com/NJU-LHRS/official-CMID/blob/c217ccde74f00e7ac8dcd6ea85964a6fc93e0de1/Pretrain/Exploring/trainer.py#L382

您好，这个位置，在pretrain的trainer文件。请问代码在下游微调的时候，是否有冻结参数呢？还是全部参数都可用微调。谢谢。

**Comment by pUmpKin-Co** [comment]
您好。

这里取决于是linear probing还是fine-tuning。fine-tuning是没有的，linear probing只会训练head而冻结其余参数。

**Comment by busbyjrj** [comment]
明白了，感谢答复！
