### ISSUE TITLE
MaskGenerator, FocalMaskGenerator, GaussianNoiseGenerator在哪里

### ISSUE THREAD

**Issue by ws1hope** [NJU-LHRS/official-CMID#4]
在Dataset/transoform.py中，MaskGenerator, FocalMaskGenerator, GaussianNoiseGenerator这三个函数没有定义也没有导入，请问在哪里呢？

**Comment by pUmpKin-Co** [comment]
您好。这些函数是实验早起用于探索不同Mask生成方式的函数，最终确定的是BlockwiseMaskGenerator。代码上传过程中忘记删除MaskTransform这个函数了，但实际上在发布版本中是没有用到的，您可以直接删除这个函数。后续我也会对代码进行更新，届时再提醒您。

感谢您对我们工作的关注。

**Comment by pUmpKin-Co** [comment]
您好。无关函数已删除，可参看`Pretrain/Dataset/transoform.py`。感谢您的反馈。
