### ISSUE TITLE
（数据集）按论文方法对Postdam进行切片，切片数与论文中说明数不一样

### ISSUE THREAD

**Issue by XuanjiaZ** [NJU-LHRS/official-CMID#7]
问题：论文切图数（21888） != 我的切图数（80408）
详细：
1. 论文中是按128的stride进行切片，得到256*256的图像，对38张6000*6000的图像切片后可以得到21888张图
2. 但是，按这种切法后，实际我得到的是80408张图，是我对切法的理解有误吗
3. 我在实际切的时候，H、W方向都是按 stride=128 进行切割的
![image](https://github.com/NJU-LHRS/official-CMID/assets/123855757/e335a420-11cb-42b3-8c0d-c0a8bca55f0c)

**Comment by pUmpKin-Co** [comment]
Closed as long periods of inactivity, feel free to reopen if there is any problem.
