### ISSUE TITLE
求助MillionAID数据集的一些问题

### ISSUE THREAD

**Issue by wangjiawen-123** [NJU-LHRS/official-CMID#8]
作者你好，想请问一下MillionAID在链接打开以后，train只有1.82G，test分别有17个文件，每个大概8G，根据您下面所写预训练是在MillionAID的testset上的，请问您是用的这17个文件嘛？还需不需要额外的txt文件呢？
MillionAID dataset: Please learn the details and download the dataset from [MillionAID](https://captain-whu.github.io/DiRS/)
For pre-training, we utilize the test-set of MillionAID dataset and load the data by PyTorch ImageFolder
期待您的回复

**Comment by pUmpKin-Co** [comment]
Hi~我当初也注意到这个问题，MillionAID只有train数据是开放了标注的，test集是没有的，但由于CMID自监督训练无需标注，就使用了test部分，也就是17个文件，不需要txt文件，全部下载下来解压即可.
谢谢您对我们工作的关注！

**Comment by pUmpKin-Co** [comment]
Closed as long periods of inactivity, feel free to reopen if there is any problem.

**Comment by HappyGoLucky6666** [comment]
作者你好，我对于MillionAID数据集也有一些疑问需要您的解答。我看到的该数据集也是包括一个训练集和17个测试集，和上面的这位老哥一样的应该。目前还在下载阶段，不过训练集较小已经下载好了。打开文件夹内部发现，您所说的train数据是开放了标注的其实就是把部分的、少量的图片分类存放起来是吗？里面并没有像其他数据集一样使用txt文件进行标注的文件吗？如果是我所说的情况的话，我在想那么不是不能够使用该数据集进行测试操作吗，毕竟他没有标记文件，无法使用其来进行模型的性能评价。这也是你们团队来使用其他数据集进行下游任务测试的原因吧。期待您的回复，谢谢！！！

> Hi~我当初也注意到这个问题，MillionAID只有train数据是开放了标注的，test集是没有的，但由于CMID自监督训练无需标注，就使用了test部分，也就是17个文件，不需要txt文件，全部下载下来解压即可. 谢谢您对我们工作的关注！

**Comment by WenLinLliu** [comment]
不懂，训练集只有1万张，test给了99万张
